export const products = [
  {
    name: "Essential Oversized Sweatshirt",
    price: 79,
    image: "https://picsum.photos/id/1027/600/750",
    tag: "Bestseller",
    colors: ["#e8e2d6", "#c9a685"],
    category: "men",
    isNewArrival: true,
    sortOrder: 1,
  },
  {
    name: "Cropped Hoodie",
    price: 65,
    image: "https://picsum.photos/id/1011/600/750",
    tag: "New",
    colors: ["#1a1a1a", "#3a3a3a", "#8a8a8a"],
    category: "women",
    isNewArrival: true,
    sortOrder: 2,
  },
  {
    name: "Utility Cargo Pants",
    price: 89,
    image: "https://picsum.photos/id/1005/600/750",
    tag: "Trending",
    colors: ["#4a4a3a", "#c9a685"],
    category: "men",
    isNewArrival: true,
    sortOrder: 3,
  },
  {
    name: "Lightweight Jacket",
    price: 120,
    image: "https://picsum.photos/id/1012/600/750",
    tag: null,
    colors: ["#5c6650"],
    category: "men",
    isNewArrival: true,
    sortOrder: 4,
  },
  {
    name: "Essential Tee",
    price: 45,
    image: "https://picsum.photos/id/1025/600/750",
    tag: null,
    colors: ["#1a1a1a", "#e8e2d6"],
    category: "women",
    isNewArrival: true,
    sortOrder: 5,
  },
];

export const testimonials = [
  {
    name: "Sarah M.",
    avatar: "https://i.pravatar.cc/100?img=47",
    rating: 5,
    verified: true,
    quote:
      "The quality is unreal. I've washed it multiple times and it still looks brand new.",
    postedAt: "2 weeks ago",
    sortOrder: 1,
  },
  {
    name: "James T.",
    avatar: "https://i.pravatar.cc/100?img=12",
    rating: 5,
    verified: true,
    quote: "Finally a brand that combines style, comfort and sustainability. Love it.",
    postedAt: "3 weeks ago",
    sortOrder: 2,
  },
  {
    name: "Priya S.",
    avatar: "https://i.pravatar.cc/100?img=32",
    rating: 5,
    verified: true,
    quote:
      "The fit is perfect and the material feels so premium. Will definitely shop again.",
    postedAt: "1 month ago",
    sortOrder: 3,
  },
];
