const photo = (id, width = 900) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${width}&q=85`;

export const products = [
  {
    slug: "essential-oversized-sweatshirt", name: "Essential Oversized Sweatshirt", subcategory: "Sweatshirts",
    price: 79, compareAtPrice: 98, image: photo("photo-1551028719-00167b16eac5"),
    images: [photo("photo-1551028719-00167b16eac5"), photo("photo-1551488831-00ddcb6c6bd3")],
    tag: "Bestseller", colors: ["Stone", "Moss"], sizes: ["XS", "S", "M", "L", "XL"],
    description: "A considered everyday layer, cut with a relaxed shoulder and a softly structured shape.",
    material: "Organic cotton fleece", fit: "Relaxed, oversized fit", care: "Wash cold inside out. Lay flat to dry.",
    rating: 4.9, reviews: 42, stock: 18, tags: ["Bestseller", "Everyday"], category: "men",
    isNewArrival: false, newArrival: false, featured: true, bestSeller: true, trending: true, sortOrder: 1,
  },
  {
    slug: "studio-cropped-hoodie", name: "Studio Cropped Hoodie", subcategory: "Sweatshirts",
    price: 65, compareAtPrice: null, image: photo("photo-1581322929500-043ae5f512d5"),
    images: [photo("photo-1581322929500-043ae5f512d5"), photo("photo-1551488831-00ddcb6c6bd3")],
    tag: "New", colors: ["Ink", "Ash", "Oat"], sizes: ["XS", "S", "M", "L", "XL"],
    description: "An easy cropped layer with a clean neckline and brushed interior for everyday comfort.",
    material: "Recycled cotton blend", fit: "Relaxed cropped fit", care: "Machine wash cold. Do not tumble dry.",
    rating: 4.8, reviews: 31, stock: 12, tags: ["New", "Soft touch"], category: "women",
    isNewArrival: true, newArrival: true, featured: true, bestSeller: false, trending: true, sortOrder: 2,
  },
  {
    slug: "utility-cargo-trouser", name: "Utility Cargo Trouser", subcategory: "Trousers",
    price: 89, compareAtPrice: null, image: photo("photo-1789938581122-d2af11a5d55a"),
    images: [photo("photo-1789938581122-d2af11a5d55a"), photo("photo-1515886657613-9f3515b0c78f")],
    tag: "Trending", colors: ["Field", "Stone"], sizes: ["28", "30", "32", "34", "36"],
    description: "Purposeful utility details meet a straight, considered silhouette in durable cotton twill.",
    material: "Cotton twill", fit: "Straight leg, mid rise", care: "Wash with similar colours at 30°C.",
    rating: 4.7, reviews: 24, stock: 9, tags: ["Trending"], category: "men",
    isNewArrival: true, newArrival: true, featured: true, bestSeller: false, trending: true, sortOrder: 3,
  },
  {
    slug: "field-canvas-jacket", name: "Field Canvas Jacket", subcategory: "Outerwear",
    price: 148, compareAtPrice: 180, image: photo("photo-1629131678696-0b56fe341b74"),
    images: [photo("photo-1629131678696-0b56fe341b74"), photo("photo-1548126032-079a0fb0099d")],
    tag: "Bestseller", colors: ["Olive", "Ink"], sizes: ["XS", "S", "M", "L", "XL"],
    description: "A durable canvas outer layer, designed to soften with wear and stay in rotation for years.",
    material: "Responsibly sourced cotton canvas", fit: "Easy, straight fit", care: "Spot clean. Professional clean when needed.",
    rating: 4.9, reviews: 18, stock: 6, tags: ["Limited"], category: "women",
    isNewArrival: false, newArrival: false, featured: true, bestSeller: true, trending: false, sortOrder: 4,
  },
  {
    slug: "everyday-heavyweight-tee", name: "Everyday Heavyweight Tee", subcategory: "T-shirts",
    price: 45, compareAtPrice: null, image: photo("photo-1790267462668-0519505ea776"),
    images: [photo("photo-1790267462668-0519505ea776"), photo("photo-1521572163474-6864f9cf17ab")],
    tag: null, colors: ["Ink", "Chalk"], sizes: ["XS", "S", "M", "L", "XL"],
    description: "A substantial cotton jersey tee with a clean finish and a little more room through the body.",
    material: "220 gsm organic cotton", fit: "Relaxed straight fit", care: "Wash cold with similar colours.",
    rating: 4.8, reviews: 57, stock: 28, tags: ["Essential"], category: "men",
    isNewArrival: true, newArrival: true, featured: true, bestSeller: true, trending: false, sortOrder: 5,
  },
  {
    slug: "everyday-crossbody", name: "Everyday Crossbody", subcategory: "Bags",
    price: 72, compareAtPrice: null, image: photo("photo-1588850561407-ed78c282e89b"),
    images: [photo("photo-1588850561407-ed78c282e89b"), photo("photo-1553062407-98eeb64c6a62")],
    tag: null, colors: ["Black", "Sand"], sizes: ["One size"],
    description: "A compact carry-all with considered compartments and an adjustable strap.",
    material: "Recycled nylon", fit: "One size, adjustable strap", care: "Wipe clean with a damp cloth.",
    rating: 4.6, reviews: 16, stock: 14, tags: ["Everyday"], category: "accessories",
    isNewArrival: false, newArrival: false, featured: true, bestSeller: false, trending: true, sortOrder: 6,
  },
  {
    slug: "relaxed-linen-shirt", name: "Relaxed Linen Shirt", subcategory: "Shirts",
    price: 96, compareAtPrice: null, image: photo("photo-1598554747436-c9293d6a588f"),
    images: [photo("photo-1598554747436-c9293d6a588f"), photo("photo-1598033129183-c4f50c736f10")],
    tag: "New", colors: ["Cloud", "Blue"], sizes: ["XS", "S", "M", "L", "XL"],
    description: "Lightweight linen with a softly relaxed shape, made for warm days and open collars.",
    material: "European flax linen", fit: "Relaxed fit", care: "Gentle wash. Hang dry for a natural texture.",
    rating: 4.9, reviews: 22, stock: 11, tags: ["New"], category: "women",
    isNewArrival: true, newArrival: true, featured: false, bestSeller: false, trending: true, sortOrder: 7,
  },
  {
    slug: "rib-knit-beanie", name: "Rib Knit Beanie", subcategory: "Hats",
    price: 38, compareAtPrice: null, image: photo("photo-1576871337622-98d48d1cf531"),
    images: [photo("photo-1576871337622-98d48d1cf531"), photo("photo-1515886657613-9f3515b0c78f")],
    tag: null, colors: ["Charcoal", "Oat"], sizes: ["One size"],
    description: "A softly structured rib knit beanie in a seasonless, easy-to-layer weight.",
    material: "Recycled wool blend", fit: "One size", care: "Hand wash cold. Dry flat.",
    rating: 4.7, reviews: 13, stock: 20, tags: ["Essential"], category: "accessories",
    isNewArrival: false, newArrival: false, featured: false, bestSeller: false, trending: false, sortOrder: 8,
  },
  {
    slug: "straight-leg-denim", name: "Straight Leg Denim", subcategory: "Denim",
    price: 110, compareAtPrice: null, image: photo("photo-1542272604-787c3835535d"),
    images: [photo("photo-1542272604-787c3835535d"), photo("photo-1541099649105-f69ad21f3246")],
    tag: "Bestseller", colors: ["Washed indigo"], sizes: ["28", "30", "32", "34", "36"],
    description: "Straight-leg denim with a soft hand feel and a subtle washed finish.",
    material: "Regenerative cotton denim", fit: "Straight leg", care: "Wash inside out with similar colours.",
    rating: 4.8, reviews: 34, stock: 15, tags: ["Bestseller"], category: "men",
    isNewArrival: false, newArrival: false, featured: false, bestSeller: true, trending: false, sortOrder: 9,
  },
  {
    slug: "weekender-tote", name: "Weekender Tote", subcategory: "Bags",
    price: 54, compareAtPrice: 68, image: photo("photo-1553062407-98eeb64c6a62"),
    images: [photo("photo-1553062407-98eeb64c6a62"), photo("photo-1588850561407-ed78c282e89b")],
    tag: null, colors: ["Natural", "Ink"], sizes: ["One size"],
    description: "A roomier everyday tote with reinforced handles and a considered inner pocket.",
    material: "Recycled cotton canvas", fit: "One size", care: "Spot clean only.",
    rating: 4.6, reviews: 19, stock: 0, tags: ["Restock soon"], category: "accessories",
    isNewArrival: false, newArrival: false, featured: false, bestSeller: false, trending: false, sortOrder: 10,
  },
];

export const testimonials = [
  {
    name: "Sarah M.",
    avatar: "https://i.pravatar.cc/100?img=47",
    rating: 5,
    verified: true,
    quote:
      "The quality is unreal. I've washed it multiple times and it still looks brand new.",
    postedAt: "2 weeks ago",
    sortOrder: 1,
  },
  {
    name: "James T.",
    avatar: "https://i.pravatar.cc/100?img=12",
    rating: 5,
    verified: true,
    quote: "Finally a brand that combines style, comfort and sustainability. Love it.",
    postedAt: "3 weeks ago",
    sortOrder: 2,
  },
  {
    name: "Priya S.",
    avatar: "https://i.pravatar.cc/100?img=32",
    rating: 5,
    verified: true,
    quote:
      "The fit is perfect and the material feels so premium. Will definitely shop again.",
    postedAt: "1 month ago",
    sortOrder: 3,
  },
];
